---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_os_family is not "RedHat" and ansible_distribution_version.split('.')[0]|int <=7
  ignore_errors: true

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_version.split('.')[0]|int }}.yml"
  when: ansible_os_family is "RedHat" and ansible_distribution_version.split('.')[0]|int > 7
  ignore_errors: true

- name: Ensure NTP-related packages are installed.
  package:
    name: "{{ ntp_ntp_package }}"
    state: present

- name: Ensure tzdata package is installed (Linux).
  package:
    name: "{{ ntp_tzdata_package }}"
    state: present
  when: ansible_system == "Linux"

- include_tasks: clock-rhel-6.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution_version.split('.')[0] == '6'

- name: Set timezone
  timezone:
    name: "{{ ntp_timezone }}"
  when: ansible_system != "SunOS"

- name: Ensure NTP is running and enabled as configured.
  service:
    name: "{{ ntp_daemon }}"
    state: started
    enabled: true
  when: ntp_enabled | bool and ansible_system != "SunOS"

- name: Ensure NTP is stopped and disabled as configured.
  service:
    name: "{{ ntp_daemon }}"
    state: stopped
    enabled: false
  when: not (ntp_enabled | bool) and ansible_system != "SunOS"

- name: Generate ntp.conf file
  template:
    src: ntp.conf.j2
    dest: "{{ ntp_conf_file }}"
  notify: restart ntp
  when: ntp_manage_config | bool
